[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quant_mp"
version = "0.1.0"
description = "Quant alg development"
requires-python = ">=3.10"
dependencies = [
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
